function outputfix(str)
    return #str % 3 == 0 and str:reverse():gsub("(%d%d%d)", "%1,"):reverse():sub(2) or str:reverse():gsub("(%d%d%d)", "%1,"):reverse()
	end


function onObjectPickUp(colour,object)

countries = {"World",
"USA",
"Spain",
"Italy",
"UK",
"France",
"Germany",
"Turkey",
"Russia",
"Iran",
"Brazil",
"Canada",
"Belgium",
"Netherlands",
"Peru",
"India",
"Switzerland",
"Portugal",
"Ecuador",
"Saudi Arabia",
"Sweden",
"Ireland",
"Mexico",
"Pakistan",
"Singapore",
"Chile",
"Israel",
"Austria",
"Belarus",
"Japan",
"Qatar",
"Poland",
"UAE",
"Romania",
"S. Korea",
"Ukraine",
"Indonesia",
"Denmark",
"Serbia",
"Philippines",
"Norway",
"Bangladesh",
"Czechia",
"Dominican Republic",
"Australia",
"Panama",
"Colombia",
"Malaysia",
"South Africa",
"Egypt",
"Finland",
"Morocco",
"Argentina",
"Kuwait",
"Algeria",
"Moldova",
"Luxembourg",
"Kazakhstan",
"Bahrain",
"Thailand",
"Hungary",
"Greece",
"Oman",
"Afghanistan",
"Iraq",
"Croatia",
"Ghana",
"Armenia",
"Uzbekistan",
"Cameroon",
"Azerbaijan",
"Iceland",
"Bosnia and Herzegovina",
"Nigeria",
"Estonia",
"Bulgaria",
"Cuba",
"Guinea",
"New Zealand",
"North Macedonia",
"Slovenia",
"Slovakia",
"Lithuania",
"Ivory Coast",
"Bolivia",
"Djibouti",
"Hong Kong",
"Tunisia",
"Senegal",
"Latvia",
"Cyprus",
"Albania",
"Honduras",
"Kyrgyzstan",
"Andorra",
"Lebanon",
"Costa Rica",
"Niger",
"Diamond Princess",
"Sri Lanka",
"Burkina Faso",
"Uruguay",
"Somalia",
"Guatemala",
"San Marino",
"Georgia",
"Mayotte",
"Channel Islands",
"DRC",
"Mali",
"Tanzania",
"Malta",
"Jordan",
"Sudan",
"Taiwan",
"Réunion",
"Kenya",
"Jamaica",
"Maldives",
"El Salvador",
"Palestine",
"Mauritius",
"Venezuela",
"Montenegro",
"Isle of Man",
"Equatorial Guinea",
"Gabon",
"Vietnam",
"Paraguay",
"Rwanda",
"Congo",
"Guinea-Bissau",
"Faeroe Islands",
"Martinique",
"Guadeloupe",
"Myanmar",
"Gibraltar",
"Liberia",
"Brunei",
"Ethiopia",
"Madagascar",
"French Guiana",
"Sierra Leone",
"Cambodia",
"Togo",
"Trinidad and Tobago",
"Cabo Verde",
"Bermuda",
"Zambia",
"Aruba",
"Eswatini",
"Monaco",
"Liechtenstein",
"Uganda",
"Bahamas",
"Barbados",
"Guyana",
"Haiti",
"Mozambique",
"Sint Maarten",
"Chad",
"Cayman Islands",
"Benin",
"Libya",
"French Polynesia",
"Nepal",
"CAR",
"Macao",
"Syria",
"Zimbabwe",
"Eritrea",
"Saint Martin",
"Mongolia",
"Malawi",
"South Sudan",
"Angola",
"Antigua and Barbuda",
"Timor-Leste",
"Botswana",
"Grenada",
"Laos",
"Belize",
"Fiji",
"New Caledonia",
"Saint Lucia",
"Curaçao",
"Dominica",
"Namibia",
"St. Vincent Grenadines",
"Saint Kitts and Nevis",
"Tajikistan",
"Nicaragua",
"Sao Tome and Principe",
"Falkland Islands",
"Turks and Caicos",
"Burundi",
"Gambia",
"Montserrat",
"Greenland",
"Vatican City",
"Seychelles",
"Suriname",
"MS Zaandam",
"Mauritania",
"Papua New Guinea",
"Bhutan",
"Yemen",
"British Virgin Islands",
"St. Barth",
"Western Sahara",
"Caribbean Netherlands",
"Anguilla",
"Comoros",
"Saint Pierre Miquelon",
"China"}

    n = math.random( #countries )
    country = countries[math.random( #countries )]
    url = "https://coronavirus-19-api.herokuapp.com/countries/" .. country
    response = WebRequest.get(url,function(a)
        broadcastToAll("Current " .. JSON.decode(a.text)["country"] .. " coronavirus cases (" .. os.date() .. "): " .. outputfix(tostring(JSON.decode(a.text)["deaths"])))
    end)
end
